[workspace]
resolver = "3"
members = [
    "crates/rsigma-parser",
    "crates/rsigma-eval",
    "crates/rsigma-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"
license = "MIT"
