[package]
name = "rsigma-cli"
description = "CLI for parsing, validating, and evaluating Sigma detection rules"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rsigma-parser = { path = "../rsigma-parser" }
rsigma-eval = { path = "../rsigma-eval" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1" }
serde_json = "1"
jaq-interpret = "1.5.0"
jaq-parse = "1.0.3"
serde_json_path = "0.7.2"
