[package]
name = "rsigma-cli"
description = "CLI for parsing, validating, linting and evaluating Sigma detection rules"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rsigma-parser = { path = "../rsigma-parser" }
rsigma-eval = { path = "../rsigma-eval" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1" }
serde_json = "1"
serde_yaml = "0.9"
jaq-interpret = "1.5.0"
jaq-parse = "1.0.3"
serde_json_path = "0.7.2"
jsonschema = "0.29"
ureq = "3"
dirs = "6"

[dev-dependencies]
assert_cmd = "2.1.2"
predicates = "3.1.4"
tempfile = "3.25.0"
