[package]
name = "rsigma-eval"
description = "Evaluator for Sigma detection rules â€” match rules against events"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rsigma-parser = { path = "../rsigma-parser" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
base64 = "0.22"
ipnet = "2"
thiserror = "2"
chrono = { version = "0.4", features = ["serde"] }
